version: 2
updates:

  - package-ecosystem: "cargo"
    directory: "examples/hello-world"
    schedule:
      interval: "monthly"

  - package-ecosystem: "cargo"
    directory: "examples/html-py-ever"
    schedule:
      interval: "monthly"

  - package-ecosystem: "cargo"
    directory: "examples/namespace_package"
    schedule:
      interval: "monthly"

  - package-ecosystem: "cargo"
    directory: "examples/rust_with_cffi"
    schedule:
      interval: "monthly"
