[build-system]
requires = ["setuptools>=46.1", "setuptools_scm[toml]>=3.4.3"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "setuptools_rust/version.py"

[tool.isort]
profile = "black"
