[package]
name = "rust_with_cffi"
version = "0.1.0"
authors = ["Alex Gaynor <alex.gaynor@gmail.com>"]
edition = "2021"

[dependencies]
pyo3 = "0.22.2"

[lib]
name = "rust_with_cffi"
crate-type = ["cdylib"]
path = "rust/lib.rs"
