[package]
name = "rust_with_cffi"
version = "0.1.0"
authors = ["Alex Gaynor <alex.gaynor@gmail.com>"]
edition = "2018"

[dependencies]
pyo3 = { version = "0.16.2", features = ["extension-module"] }

[lib]
name = "rust_with_cffi"
crate-type = ["cdylib"]
