[package]
name = "html-py-ever"
version = "0.1.0"
authors = ["konstin <konstin@mailbox.org>"]
edition = "2018"

[dependencies]
kuchiki = "0.8.0"
pyo3 = { version = "0.17.1", features = ["extension-module"] }
tendril = "0.4.3"

[lib]
name = "html_py_ever"
crate-type = ["cdylib"]
